### ISSUE TITLE
⬆️ Update ipywidgets

### ISSUE THREAD

**Issue by ollyhensby** [maxfordham/ipyautoui#141]
ipywidgets and other dependencies need updating following the release of [ipywidgets 8.0.5](https://github.com/jupyter-widgets/ipywidgets/releases/tag/8.0.5):

```
ipywidgets==8.0.5
jupyterlab_widgets==3.0.6
widgetsnbextension==4.0.6
comm==0.1.3
```

**Comment by jgunstone** [comment]
we currently don't pin these dependencies: 

https://github.com/maxfordham/ipyautoui/blob/0d2b731efaef1dc526bbbd820e1ef9a01897d40c/pyproject.toml#L18-L35
