### ISSUE TITLE
jsonref for attaching refs to jsonschema ? 

### ISSUE THREAD

**Issue by ollyhensby** [maxfordham/ipyautoui#165]
I found this ;
https://github.com/gazpachoking/jsonref

could potentially simplify this code : 
https://github.com/maxfordham/ipyautoui/blob/9073e5fab4808cc6b5f37cc03ec1e35ccc6d4fbc/src/ipyautoui/automapschema.py#LL68C5-L68C23

...

**Comment by jgunstone** [comment]
merged to main in this PR https://github.com/maxfordham/ipyautoui/pull/199
