### ISSUE TITLE
🐛DisplayPaths 403 Voila Issue

### ISSUE THREAD

**Issue by ollyhensby** [maxfordham/ipyautoui#169]
**Explain the issue**
Can't seem to preview PDF file in voila. This is what appears:
![image](https://github.com/maxfordham/ipyautoui/assets/79875276/9fc160f1-b13d-4d21-827a-6e6fd743174b)

This does work in Jupyter Notebook though.

This is most likely a Voila issue will also create an issue on there and link it here.

**Comment by jgunstone** [comment]
when displaying in Voila there is a requirement to explicitly whitelist files you want to be able to serve: 

https://voila.readthedocs.io/en/stable/customize.html#serving-static-files
