### ISSUE TITLE
✨ host docs using gh-pages and gh-actions

### ISSUE THREAD

**Issue by jgunstone** [maxfordham/ipyautoui#208]
https://jupyterbook.org/en/stable/publish/gh-pages.html#automatically-host-your-book-with-github-actions

**Comment by jgunstone** [comment]
https://github.com/maxfordham/ipyautoui/blob/main/.github/workflows/deploy-book.yml

seems to work: 
https://maxfordham.github.io/ipyautoui/

though not sure why it is only showing the readme...

**Comment by ollyhensby** [comment]
The issue was that in the Pages settings, it was set to look at `main` instead of `gh-pages`. I've changed it to look at `gh-pages`.

**Comment by jgunstone** [comment]
great spot - thanks for sorting this! 
now the docs are actually working I spotted a few errors but we can pick those up in another issue.
