### ISSUE TITLE
✨ Make BUTTON_BAR_CONFIG configurable

### ISSUE THREAD

**Issue by ollyhensby** [maxfordham/ipyautoui#264]
**Is your feature request related to a problem? Please describe.**
It would be great if the BUTTON_BAR_CONFIG was configurable for custom EditGrids.

https://github.com/maxfordham/ipyautoui/blob/33191603334482b28dcfe0f0fabaae3052437e92/src/ipyautoui/custom/buttonbars.py#L255-L392

**Describe the solution you'd like**
Define a dataclass that defines the fields required for each of the buttons in EditGrid.

```python
from dataclasses import dataclass

@dataclass
class ButtonBarConfig:
    tooltip: str
    tooltip_clicked: str
    button_style: str
    message: str

@dataclass
class CrudButtonBarConfig:
    add: ButtonBarConfig
    edit: ButtonBarConfig
    copy: ButtonBarConfig
    delete: ButtonBarConfig

# Example usage:
crud_config = CrudButtonBarConfig(
    add=ButtonBarConfig(
        tooltip="add item",
        tooltip_clicked="Go back to table",
        button_style="success",
        message="  ➕ <i>Adding Value</i>"
    ),
    edit=ButtonBarConfig(
        tooltip="edit item",
        tooltip_clicked="Go back to table",
        button_style="success",
        message="  ✏️ <i>Editing Value</i>"
    ),
    copy=ButtonBarConfig(
        tooltip="copy item",
        tooltip_clicked="Go back to table",
        button_style="success",
        message="  📝 <i>Copying Value</i>"
    ),
    delete=ButtonBarConfig(
        tooltip="delete item",
        tooltip_clicked="Go back to table",
        button_style="success",
        message="  🗑️ <i>Deleting Value</i>"
    )
)
```

`CrudButtonBarConfig` could then be used within the class `CrudButtonBar` for the `active` trait:

https://github.com/maxfordham/ipyautoui/blob/33191603334482b28dcfe0f0fabaae3052437e92/src/ipyautoui/custom/buttonbars.py#L296-L297

Maybe `active` needs renaming to something like `config`?

**Comment by jgunstone** [comment]
good spot - looks like this functionality was only partially implemented... will take a look

**Comment by ollyhensby** [comment]
- [ ] Use TypedDicts to define structure
- [ ] Implement into CrudButtonBar
- [ ] Make it a traitlet, `CrudView`
- [ ] Remove `active` if not in use
- [ ] Replace `names` with `CrudView` keys
- [ ] Add _post_init for adding custom buttons e.g. images
