### ISSUE TITLE
🎨 Add black formatting

### ISSUE THREAD

**Issue by ollyhensby** [maxfordham/ipyautoui#316]
**Describe the upkeep / improvement you'd like to see**
A lot of the modules are not formatting correctly with black. There are also some docstrings which are incomplete that either need removing or reviewing.

**Comment by jgunstone** [comment]
good idea - 
I think we can also remove anywhere where we use the following also: 

```py
# %run _dev_maplocal_params.py
# %load_ext lab_black
```

can we wait until I've closed out #312 ?

**Comment by jgunstone** [comment]
@ollyhensby - maybe you could pick this up once #318 is merged?
