### ISSUE TITLE
🐛 Inconsistency between `.value` and `.selected` in `custom.FileChooser`

### ISSUE THREAD

**Issue by mwcraig** [maxfordham/ipyautoui#336]
**Describe the bug**

To watch changes on a `FileChooser`, you observe the `_value` traitlet. Because of where that is set, a handler that is observing changes in `_value` will see an inconsistent state of the `FileChooser`: the `_value` and the `selected` attrubutes will have different values.

**To Reproduce**

```python
from pathlib import Path
from ipyautoui.custom import FileChooser

# Make a file so that we can set the value of FileChooser
p = Path("./dummy.txt")
p.touch()

# Make a FileChooser
fc = FileChooser()

# Define an observer that just prints the state of the FileChooser
def print_status(change):
    print(f"{change['new']=}")
    print(f"{fc.selected=}")
    print(f"{fc._value=}")

# Observe the _value traitlet
fc.observe(print_status, "_value")

# set the value
fc.value = str(p)
```

This produces the output

```
change['new']='dummy.txt'
fc.selected=None
fc._value='dummy.txt'
```

**Expected behavior**
 
Ideally, `selected` should be consistent with `_value`. I think that can be done by moving [this line](https://github.com/maxfordham/ipyautoui/blob/766edaee2e806ab8a8ab79df07eb63ddb299d7fe/src/ipyautoui/custom/filechooser.py#L62) later in the method.

Then the output would be:

```
change['new']='dummy.txt'
fc.selected='dummy.txt;
fc._value='dummy.txt'
```

**Screenshots**

N/A

**Additional context**

Arguably the fix is to use `change['new']` in the handler instead attributes on the `FileChooser`.....

**Comment by jgunstone** [comment]
thanks - good spot - I moved the value setter to the end as you suggested and it seems to have fixed it
