### ISSUE TITLE
♻️ docs CI failing

### ISSUE THREAD

**Issue by jgunstone** [maxfordham/ipyautoui#338]
![image](https://github.com/user-attachments/assets/478ab41a-014a-47a7-b4d3-7be77766dee9)

**Comment by ollyhensby** [comment]
I think this is failing because `sphinxcontrib-serializinghtml` after `1.1.5` requires `sphinx>=5.0`. Will pin `sphinxcontrib-serializinghtml` to `1.1.5` and see if that resolves the issue for now.

**Comment by jgunstone** [comment]
maybe we should have a look at https://github.com/machow/quartodoc and quarto generally for the docs now that we are more versed in that...
