### ISSUE TITLE
Release plans

### ISSUE THREAD

**Issue by mwcraig** [maxfordham/ipyautoui#68]
👋  @jgunstone we met at the Future of Jupyter Widgets workshop a few weeks ago. I'd really like to try out `ipyautoui` in a project I'm working on (the notebook pieces of https://github.com/feder-observatory/stellarphot) but to do that I'd need there to be a release that can be pip installed. In addition to the auto UI functionality, I'm potentially also interested in the auto run piece. The last piece I'm eager to use is your `FileChooser` wrapper.

I'm happy to help with getting a release ready if you need help, though I won't have a ton of availability until classes end on Dec 6.

I've got a lot of experience with conda-forge, so I'm happy to help with that piece of the packaging puzzle.

**Comment by jgunstone** [comment]
Hi @mwcraig - apologies - i missed this issue. 
Thanks for the prompt - i've been dragging my heals a bit with the packaging! 
i just released: https://github.com/maxfordham/ipyautoui/releases/tag/0.3.0

and put it on PyPi 🎉
https://pypi.org/project/ipyautoui/0.3.0/

try the demo function

```py
from ipyautoui import demo
demo()
```
![image](https://user-images.githubusercontent.com/21370980/204035249-83934051-ad1f-4367-b262-4f88052df7e2.png)

and there is an example of the `FileChooser` that you were interested in. 

Let me know if you have any issues, I'm quite green to this packaging game so expecting a few 🐛s

**Comment by mwcraig** [comment]
Thank you! Just installed and it seems to be working fine!

**Comment by jgunstone** [comment]
great news :) 
I'm trying to package for conda-forge... 
I'm using a package [traitlets_paths](https://github.com/Zsailer/traitlets_paths) that isn't on conda - 
I created a feedstock here and tried to merge:
https://github.com/conda-forge/staged-recipes/pull/21318

I had this issue with the License: 
https://github.com/conda-forge/staged-recipes/pull/21318#issuecomment-1328249366 , do you know what this could be?

once that is done I'll move onto `ipyautoui`

**Comment by jgunstone** [comment]
haven't added to conda yet but its on PyPi so i'm gonna close here.
cheers
