### ISSUE TITLE
Add and Edit Open Simultaneously

### ISSUE THREAD

**Issue by ollyhensby** [maxfordham/ipyautoui#88]
![image](https://user-images.githubusercontent.com/79875276/210391382-6ccb4c3e-3986-46de-8f42-322c51a1eff2.png)

The snapshot above shows both Add and Edit options open at the same time.

Add should close when Edit is clicked and vice-versa.

It may be worth updating the button bar UI object to ipywidgets.ToggleButtons.

**Comment by jgunstone** [comment]
resolved by this: 
https://github.com/maxfordham/ipyautoui/pull/97
